### ISSUE TITLE
请问emqtt的开源的协议是什么？可以商用吗?

### ISSUE THREAD

**Issue by andywang2014** [emqtt/docs_zh#1]
请问emqtt的开源的协议是什么？可以商用吗?

**Comment by erylee** [comment]
Apache License Version 2.0. Could be used in your commercial product.

**Comment by andywang2014** [comment]
ok,thank you.

**Comment by andywang2014** [comment]
有推荐的java客户端实现来测试吗？

**Comment by erylee** [comment]
http://www.eclipse.org/paho/#
